# Application properties for the Flow application
spring.application.name=flow
server.port=8081

# Enable Spring DevTools for hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#Loggin settings 
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace

# Database configuration using environment variables
spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
server.servlet.session.timeout=120m


# Show SQL statements in the console
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT configuration using environment variables(일단 주석)
#jwt.secret=${JWTKEY}
#jwt.expiration-ms=86400000


# OAuth2 client configuration for Google (일단 주석)
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#spring.security.oauth2.client.registration.google.scope=profile,email
# ?? ??? ?? ?? ?? ??? ??? ???
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/api/login/oauth2/code/google
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/api/login/oauth2/code/google

# OAuth2 client configuration for Kakao (일단 주석)
#spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
#spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}
#spring.security.oauth2.client.registration.kakao.scope=profile_nickname,account_email
#spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/api/login/oauth2/code/kakao
#spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8081/api/login/oauth2/code/kakao


# Email configuration using enviroment variables
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAILUSER}
#spring.mail.password=${MAILPASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true